const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"档案",
                        "menuJump":"列表",
                        "tableName":"dangan"
                    }
                ],
                "menu":"档案"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"党课",
                        "menuJump":"列表",
                        "tableName":"dangke"
                    }
                ],
                "menu":"党课"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"党课收藏",
                        "menuJump":"列表",
                        "tableName":"dangkeCollection"
                    }
                ],
                "menu":"党课收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"党课评价",
                        "menuJump":"列表",
                        "tableName":"dangkeCommentback"
                    }
                ],
                "menu":"党课评价"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-order",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"党课报名",
                        "menuJump":"列表",
                        "tableName":"dangkeOrder"
                    }
                ],
                "menu":"党课报名"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"试卷选题",
                        "menuJump":"列表",
                        "tableName":"exampapertopic"
                    }
                ],
                "menu":"试卷选题"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"公告信息",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告信息"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                            "新增",
                        ],
                        "menu":"签到信息",
                        "menuJump":"列表",
                        "tableName":"kaoqin"
                    }
                ],
                "menu":"签到信息"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                            "新增",
                        ],
                        "menu":"谈心谈话",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"谈心谈话"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                            "新增",
                        ],
                        "menu":"入党申请",
                        "menuJump":"列表",
                        "tableName":"shenqingYuyue"
                    }
                ],
                "menu":"入党申请"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"提醒",
                        "menuJump":"列表",
                        "tableName":"tixing"
                    }
                ],
                "menu":"提醒"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"在线学习",
                        "menuJump":"列表",
                        "tableName":"xuexi"
                    }
                ],
                "menu":"在线学习"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"在线学习收藏",
                        "menuJump":"列表",
                        "tableName":"xuexiCollection"
                    }
                ],
                "menu":"在线学习收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"在线学习留言",
                        "menuJump":"列表",
                        "tableName":"xuexiLiuyan"
                    }
                ],
                "menu":"在线学习留言"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"作业",
                        "menuJump":"列表",
                        "tableName":"zuoye"
                    }
                ],
                "menu":"作业"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                            "新增",
                        ],
                        "menu":"作业提交",
                        "menuJump":"列表",
                        "tableName":"zuoyeTijiao"
                    }
                ],
                "menu":"作业提交"
            }
			,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-rank",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"错题本",
                        "tableName":"examrewrongquestion"
                    },
                    {
						"appFrontIcon":"cuIcon-list",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"试卷列表",
                        "tableName":"exampaper"
                    },
                    {
						"appFrontIcon":"cuIcon-footprint",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"考试记录",
                        "tableName":"examrecord"
                    }
                ],
                "menu":"考试管理"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
